import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  cartItems: [],
};

const CartSlice = createSlice({
  name: "cart",
  initialState,
  reducers: {
    // state - current state of the slice
    // action - dispatched action containing the payload
    // If the item already exists in the cart, increment its quantity. Otherwise, add it to the cart with a quantity of 1.
    addItemToCart(state, action) {
      const existingItem = state.cartItems.find(
        (item) => item.id === action.payload.id,
      );
      if (existingItem) {
        existingItem.quantity += 1;
      } else {
        state.cartItems.push({ ...action.payload, quantity: 1 });
      }
    },

    // Remove items from the cart based on their ID.
    removeItemsFromCart(state, action) {
      state.cartItems = state.cartItems.filter(
        (item) => item.id !== action.payload,
      );
    },

    // Clear all items from the cart.
    clearCart(state) {
      state.cartItems = [];
    },

    // If the item exists in the cart, increment its quantity by 1.
    increaseItemQuantity(state, action) {
      const itemToIncrease = state.cartItems.find(
        (item) => item.id === action.payload,
      );
      if (itemToIncrease) {
        itemToIncrease.quantity += 1;
      }
    },

    // If the item exists in the cart and its quantity is greater than 1, decrement its quantity by 1.
    decreaseItemQuantity(state, action) {
      const itemToDecrease = state.cartItems.find(
        (item) => item.id === action.payload,
      );
      if (itemToDecrease && itemToDecrease.quantity > 1) {
        itemToDecrease.quantity -= 1;
      }
    },
  },
});

// Export the action creators generated by createSlice for use in dispatching actions to the store.
export const {
  addItemToCart,
  removeItemsFromCart,
  clearCart,
  increaseItemQuantity,
  decreaseItemQuantity,
} = CartSlice.actions;

export default CartSlice.reducer;
